[build]
command = "ng build --configuration production"
publish = "dist/client"

[[plugins]]
package = "@netlify/angular-runtime"

  [plugins.inputs]
  skip = true

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
